M48
; DRILL file {KiCad 7.0.6} date Sun Apr  7 09:56:10 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-04-07T09:56:10-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0390
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X6.34Y-3.514
X6.54Y-3.474
X6.54Y-3.554
T2
X5.58Y-2.8305
X5.58Y-3.7305
X6.28Y-2.8305
X6.28Y-3.7305
T0
M30
