M48
; DRILL file {KiCad 7.0.6} date Sun Aug 20 20:53:25 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-08-20T20:53:25-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X5.58Y-2.8305
X5.58Y-3.7305
X6.28Y-2.8305
X6.28Y-3.7305
T0
M30
